# Generated by Django 4.2 on 2023-05-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productdetails_delete_inventory_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
