# Generated by Django 4.2 on 2023-05-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
