# Generated by Django 4.2 on 2023-05-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0002_alter_paymenttoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
